/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-error-container": "#ffdad6",
        "surface-bright": "#38393f",
        "surface-dim": "#121318",
        "on-secondary-fixed": "#2c0051",
        "on-secondary-fixed-variant": "#6900b3",
        "error": "#ffb4ab",
        "on-tertiary-fixed-variant": "#653e00",
        "primary-container": "#00f2fe",
        "on-surface-variant": "#b9cacb",
        "inverse-surface": "#e3e1e9",
        "on-secondary-container": "#d6a9ff",
        "outline-variant": "#3a494b",
        "tertiary": "#fff5ee",
        "on-primary": "#00373a",
        "on-tertiary": "#472a00",
        "surface-tint": "#00dce6",
        "secondary-fixed": "#f0dbff",
        "on-surface": "#e3e1e9",
        "primary": "#e0fdff",
        "secondary": "#ddb7ff",
        "secondary-fixed-dim": "#ddb7ff",
        "inverse-on-surface": "#2f3036",
        "background": "#121318",
        "surface-container-low": "#1a1b21",
        "secondary-container": "#6f00be",
        "inverse-primary": "#00696f",
        "surface-container-high": "#292a2f",
        "on-tertiary-fixed": "#2a1700",
        "surface-variant": "#34343a",
        "surface-container": "#1e1f25",
        "on-primary-fixed-variant": "#004f53",
        "error-container": "#93000a",
        "on-primary-container": "#006a70",
        "tertiary-container": "#ffd3a1",
        "on-primary-fixed": "#002022",
        "on-tertiary-container": "#875400",
        "primary-fixed-dim": "#00dce6",
        "surface-container-lowest": "#0d0e13",
        "on-error": "#690005",
        "tertiary-fixed": "#ffddb8",
        "outline": "#849495",
        "surface": "#121318",
        "tertiary-fixed-dim": "#ffb95f",
        "on-secondary": "#490080",
        "on-background": "#e3e1e9",
        "primary-fixed": "#6ff6ff",
        "surface-container-highest": "#34343a"
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem"
      },
      spacing: {
        "space-3xl": "4.5rem",
        "gutter-tablet": "1rem",
        "grid-margin-tablet": "1.5rem",
        "space-xl": "2rem",
        "space-xs": "0.5rem",
        "space-2xl": "3rem",
        "space-2xs": "0.25rem",
        "grid-margin-mobile": "1rem",
        "space-sm": "0.75rem",
        "gutter-desktop": "1.5rem",
        "space-lg": "1.5rem",
        "gutter-mobile": "0.75rem",
        "grid-margin-desktop": "3rem",
        "space-md": "1rem"
      },
      fontFamily: {
        "headline-lg": ["Space Grotesk", "sans-serif"],
        "headline-sm": ["Space Grotesk", "sans-serif"],
        "display-hero-mobile": ["Space Grotesk", "sans-serif"],
        "display-hero": ["Space Grotesk", "sans-serif"],
        "body-lg": ["Chivo", "sans-serif"],
        "body-sm": ["Chivo", "sans-serif"],
        "body-md": ["Chivo", "sans-serif"],
        "headline-lg-mobile": ["Space Grotesk", "sans-serif"],
        "headline-md": ["Space Grotesk", "sans-serif"],
        "label-data-md": ["JetBrains Mono", "monospace"],
        "label-data-lg": ["JetBrains Mono", "monospace"],
        "label-data-sm": ["JetBrains Mono", "monospace"]
      }
    },
  },
  plugins: [],
}
